### ISSUE TITLE
**Nura** 4-[Javascript Variables (10min)](https://youtu.be/glLCsD8rlzA)

### ISSUE THREAD

**Issue by alimbaeva** [BrightBrainsKk/Section-9#2]
Нура я создала репозиторий, ты туда можешь форкнуть, и посмотри как я сделала, я каждому уроку создала отдельный файл скрипта, и в этот файл писала, А те темы который объемные можешь создать файл и загрузить а другие напишут свой код туда

**Comment by nuranurbekova** [comment]
done
